<? foreach ( $fieldList as $field ) : ?>
	
<? if ( $field['Key'] === "PRI" ) : ?>	
<input type="hidden" name="<?=$field['Field']?>" id="field-<?=$field['Field']?>" value="" />
<? continue ?>
<? endif ?>

<div class="form-group">
	<label for="field-<?=$field['Field']?>"><?=$field['Label']?>:</label>
<? if ( $field['Inputtype'] === "textarea" ) : ?>
	<textarea name="<?=$field['Field']?>" maxlength="65535" class="form-control" id="field-<?=$field['Field']?>" placeholder="<?=$field['Label']?>" ></textarea>
<? else : ?>
	<input value="" name="<?=$field['Field']?>" type="<?=$field['Inputtype']?>" maxlength="<?=$field['Maxlength']?>" class="form-control" id="field-<?=$field['Field']?>" placeholder="<?=$field['Label']?>" />
<? endif ?>

</div>
<? endforeach ?>