<? foreach ( $fieldList as $field ) : ?>
	
<? if ( $field['Key'] === "PRI" ) : ?>	
<input type="hidden" name="<?=$field['Field']?>" id="<?=$field['Inputid']?>" value="" />
<? continue ?>
<? endif ?>

<div class="form-group">
	<label for="<?=$field['Inputid']?>"><?=$field['Label']?>:</label>
<? if ( $field['Inputtype'] === "textarea" ) : ?>
	<textarea name="<?=$field['Field']?>" <?=$field['Requiredattribute']?> maxlength="65535" class="form-control" id="<?=$field['Inputid']?>" placeholder="<?=$field['Label']?>" ></textarea>
<? else : ?>
	<input value="" name="<?=$field['Field']?>" type="<?=$field['Inputtype']?>" <?=$field['Requiredattribute']?> maxlength="<?=$field['Maxlength']?>" class="form-control" id="<?=$field['Inputid']?>" placeholder="<?=$field['Label']?>" />
<? endif ?>

</div>
<? endforeach ?>